### ISSUE TITLE
Applying a lemma or to rewrite in hypothesis

### ISSUE THREAD

**Issue by NotBad4U** [Deducteam/lambdapi#1166] opened 2024-12-22 13:07 UTC
Hi everyone!

I often work with proof that does forward reasoning (automatic solver style), which involves working on the hypothesis.
The current Lambdapi tactics set does not provide a feature to apply a symbol on a hypothesis e.g. `apply x in H` or `rewrite x in H`. Should we consider adding this feature? Is it not to hard to implement with the current [proof_state](https://github.com/Deducteam/lambdapi/blob/50f02fc636f69a5c797e9ea2fcd9e6473c6cf073/src/handle/proof.ml#L113)?

**Comment by fblanqui** [comment] 2024-12-22 13:59
Yes, this feature would be useful. I close it because this is a duplicate of #671 . We can continue the discussion there.

**Closed by fblanqui** 2024-12-22 13:59 UTC
