### ISSUE TITLE
rewrite under quantifiers

### ISSUE THREAD

**Issue by bodeveix** [Deducteam/lambdapi#1120] opened 2024-06-20 20:49 UTC
The rewrite tactic fails to cross quantifiers as shown in the proof of the "bug" theorem of the attached file.

[bug3.txt](https://github.com/user-attachments/files/15919969/bug3.txt)

**Comment by fblanqui** [comment] 2024-06-21 05:08
Thank you for the issue. This is a known issue indeed. I close it since it is a duplicate of #694 .

**Closed by fblanqui** 2024-06-21 05:08 UTC

**Comment by fblanqui** [comment] 2025-03-14 13:51
There is a difference with #694 though which is that the LHS is closed and does not contain variables that can be instantiated by terms containing bound variables.
