### ISSUE TITLE
Problem with conversion with an AC symbol

### ISSUE THREAD

**Issue by Thiagofelis** [Deducteam/lambdapi#644] opened 2021-04-11 10:57 UTC
I'm having the following problem with an AC symbol. The following typechecks normally. The assertion verifies one step of the rewriting rule.
```
symbol Nat : TYPE;
symbol plus_N : Nat → Nat → Nat;

symbol Lvl : TYPE;
symbol LvlSet : TYPE;

symbol Max : Nat → LvlSet → Lvl;
symbol Plus : Nat → Lvl → LvlSet;
symbol mapPlus : Nat → LvlSet → LvlSet;

symbol Union : LvlSet → LvlSet → LvlSet;

rule Max $i   (Union (Plus $j (Max $k $l)) $tl) ↪ Max (plus_N $i (plus_N $j $k)) (Union (mapPlus $j $l) $tl);


assert a b c d ⊢  Max c (Union (Plus c (Max c b)) d) ≡ 
                Max (plus_N c (plus_N c c)) (Union (mapPlus c b) d);
```
But when I make Union an AC symbol this doesn't typecheck anymore:
```
symbol Nat : TYPE;
symbol plus_N : Nat → Nat → Nat;

symbol Lvl : TYPE;
symbol LvlSet : TYPE;

symbol Max : Nat → LvlSet → Lvl;
symbol Plus : Nat → Lvl → LvlSet;
symbol mapPlus : Nat → LvlSet → LvlSet;

associative commutative symbol Union : LvlSet → LvlSet → LvlSet;

rule Max $i   (Union (Plus $j (Max $k $l)) $tl) ↪ Max (plus_N $i (plus_N $j $k)) (Union (mapPlus $j $l) $tl);


assert a b c d ⊢  Max c (Union (Plus c (Max c b)) d) ≡ 
                Max (plus_N c (plus_N c c)) (Union (mapPlus c b) d);
```
I get Assertion failed. Is there a reason for this not to work with an AC symbol?

My version is 8609ec21

**Comment by fblanqui** [comment] 2021-04-13 11:15
Thanks for the report Thiago. I see the problem. LHS should not be normalized. I'll try to fix this.

**Comment by fblanqui** [comment] 2021-04-13 17:18
The problem is fixed in #645. Note however that you need to be careful when adding rules containing C or AC symbols. For instance, in your example, you need to add the rule
```
 rule Max $i (Union $tl (Plus $j (Max $k $l))) ↪ Max (plus_N $i (plus_N $j $k)) (Union (mapPlus $j $l) $tl);
```
This is the same rule as the one that you have given except that, in the LHS, the arguments of Union are permuted.
Otherwise you loose (local) confluence modulo the equations: the reduction relation is not complete wrt the equational theory (reflexive, symmetric and transitive closure of rules).
This completion could be done automatically in the case of C symbols.
For AC symbols, this may be more complicated.
So, for the moment, this is left to the user.

**Comment by fblanqui** [comment] 2021-04-13 17:20
Thanks @Thiagofelis to tell me if this fix is fine for you or if you have other problems.

**Comment by Thiagofelis** [comment] 2021-04-13 17:24
Ok thanks Frédéric, I'm just waiting for the merge and then I'll test it. So if I understood correctly the matching is not done modulo AC, as was the case in Dedukti?

**Comment by fblanqui** [comment] 2021-04-13 18:05
Exactly. You can test the branch directly by doing:
```
git remote add frederic https://github.com/fblanqui/lambdapi
git fetch frederic
git checkout frederic/ac
```

**Comment by Thiagofelis** [comment] 2021-04-13 19:42
Ok thanks. From what I understand, I think that for the encoding to work we would need AC matching. For instance, 
```
Max $i ($tl U ((Plus $j (Max $k $l)) U $tl))
```
would not be matched, whereas the following would.
```
Max $i (($tl U $tl) U (Plus $j (Max $k $l)))
```
There's might be a workaround, but I would need to think a bit more.

Anyway, I've made some tests and I'm getting some weird errors, probably something stupid I'm doing. I'll let you know once I understand more whats going on.

**Comment by fblanqui** [comment] 2021-04-14 05:44
For C symbols, you need to have 2^n rules where n is the number of C symbols in the LHS, by enumerating all the permutations of the arguments of the C symbols. Said otherwise, the set R of rules must be closed by the following property: if l-->r belongs to R and l ~_C l', then l'-->r belongs to R.

**Comment by Thiagofelis** [comment] 2021-04-14 06:51
Yes, and that's what we do by having the two rules
```
rule Max $i ((Plus $j (Max $k $l)) U $tl) ↪ Max (plus_N $i (plus_N $j $k)) (Union (mapPlus $j $l) $tl);
rule Max $i ($tl U (Plus $j (Max $k $l))) ↪ Max (plus_N $i (plus_N $j $k)) (Union (mapPlus $j $l) $tl);
```
So this set of rules is closed with respect to ~_C. However, what I was saying is that neither of the two rules matches 
```
Max $i ($tl U ((Plus $j (Max $k $l)) U $tl))
```
whereas, if I've understood correctly, this would be matched in the Dedukti.

So we would need for it to be closed under ~_AC also, but the problem here is that the number of AC symbols in this LHS is a priori unknown, there could be arbitrarily many of these symbols nested. For instance, I could add the rule
```
rule Max $i ($tl U ((Plus $j (Max $k $l)) U $tl)) ↪ Max (plus_N $i (plus_N $j $k)) (Union (mapPlus $j $l) $tl);
```
and of course all of its permutations. But know if I want to match
```
Max $i ($tl U (($tl U (Plus $j (Max $k $l))) U $tl))
```
I need to add another rule, and this goes on.

**Comment by fblanqui** [comment] 2021-04-14 13:29
When you have associativity, you need to add what is usually called "extension rules". Because you have Max i ((a U t) U t') ~_A Max i (a U (t U t')) --> r when a = Plus j (Max k l), you need to add the rule Max i ((a U t) U t') --> r and complete wrt C:
```
rule Max $i (((Plus $j (Max $k $l)) U $t) U $t') ↪ Max (plus_N $i (plus_N $j $k)) (Union (mapPlus $j $l) ($t U $t'));
```
However, this may not be sufficient in your case (unless perhaps if we use an ordering on arguments in which terms of the form Plus _ _ are smaller than variables).
The point is that you require rewriting with matching modulo AC while Lambdapi only provides rewriting with syntactic matching and conversion modulo AC.
Adding matching modulo AC is non trivial. So it would be nice to first make sure that matching modulo AC is really needed for checking terms obtained by translating Coq or Agda terms. And even if some encoding requires matching modulo AC, it may be the case that another encoding does not require matching modulo AC.

**Closed** 2021-04-14 16:00 UTC
