### ISSUE TITLE
Adding `let ... in ...` in the abstract syntax

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/lambdapi#222] opened 2019-06-18 07:13 UTC
Translating CIC into Dedukti requires to have a translation for the `let ... in ...` construction.

The trick used for Matita with Krajono and Coq for CoqInE is the following: Assume that we want to translate `let x:a = n in m` in a context `x_i:A_i`. Then first we introduce a definition:

```
def let_x : x_i:[A_i] -> [a] = (x_i : [A_i]) => [n]
```

Then `[m]` is translated as `[m{x<- let_x x_i}]`. By laziness, I don't print all the `x_i`, However I hope that it is clear that `x_i` and `A_i` is a list of an arbitrary size.

The problem with this is that the size of the translation is quadratic with respect to the original term. While in the arithmetic library of Matita, this was not a real issue since the proofs did not use many `let ... in ...`, it is quite an issue today while @Gaspi started to translate GeoCoq in Dedukti. Indeed, many proofs of the library use a lot of assertions which are translated by a `let ... in ...` (see [this file ](https://github.com/Deducteam/GeoCoqInE/blob/master/Elements/OriginalProofs/lemma_35helper.v) for example).

To overcome this issue, I see two solutions:
- Some `let ... in ...` can be translated by a beta redex if the binding `{x <- n}` is not used to type `m`.
The translator should be able to detect this case and in that case, translate the binding by a beta redex
- We add a `let ... in ...` in the abstract syntax of Dedukti. 

In both cases, we need to provide a concrete syntax for a `let ... in ...` construction. From #208 I see that this is already the case in the new syntax. In the old syntax, this has been handled by @Gaspi in [This PR](https://github.com/Deducteam/Dedukti/pull/131)

**Comment by fblanqui** [comment] 2019-06-18 20:10
In LP, let's are allowed in the concrete syntax and translated at parsing time into a beta redex (this is syntactic sugar). Isn't it sufficient? Why do you need let in the `term` type?

**Comment by francoisthire** [comment] 2019-06-18 21:23
That's the kind of example I am talking about:

```coq
Inductive VecB : nat -> Set :=
| Nil : VecB 0
| Cons : forall n, bool -> VecB n -> VecB (S n).

Definition foo :=
  let x : nat      := 0 in
  let l : VecB x := Nil in
  l = l.

Definition foo' :=
  let x : nat := 0 in
  (fun l  : VecB x => l = l) Nil.

Fail Definition foo'' :=
  (fun x : nat => (fun l : VecB x => l) Nil) 0.
```

**Comment by fblanqui** [comment] 2019-06-19 08:27
It's no problem in LP:
```
require open Set Nat Bool Logic

symbol vec : N⇒Set
definition V n ≔ S (vec n)
symbol nil : V 0
symbol cons : B⇒∀n,V n⇒V(succ n)

definition foo ≔ let x = 0 in let v = nil in v=v

definition foo2 ≔ (λx,(λl,l)nil)0
```

**Comment by GuillaumeGen** [comment] 2019-06-19 08:42
The problem is the `VecB x` annotation.
It is impossible to give a type to `l` such that `fun x : nat => (fun l : _ => l)` can be applied to any value.

**Comment by francoisthire** [comment] 2019-06-19 09:01
@fblanqui I think you are cheating here since you don't provide annotations for abstractions. Here another example, which I think, would fail:

```coq
Inductive VecB : nat -> Set :=
| Nil : VecB 0
| Cons : forall n, bool -> VecB n -> VecB (S n).

Parameter bar : forall (x : nat), VecB x.

Definition foo :=
  let x : nat      := 0 in
  let l : VecB x := Nil in
  l = l /\ l = bar x.

Definition foo' :=
  let x : nat := 0 in
  (fun l  : VecB x => l = l /\ l = bar x) Nil.
```

**Comment by rlepigre** [comment] 2019-06-19 09:06
Well, this is all related to the fact that if you define the `let` as
a redex (as we have done so far), then it is typed as follows.
```
     Γ, x:A ⊢ u : B
  -------------------- ∀i
   Γ ⊢ λx.u : ∀x∈A, B         Γ ⊢ t : A
  -------------------------------------- ∀e
         Γ ⊢ (λx.u) t : B[x := t]
     ================================
      Γ ⊢ let x = t in u : B[x := t]
```
However, this is too weak because in the premisse for `u` you lose the
equation `x ≡ t`.

The expected rule for the `let` should b something like the following.
```
   Γ, x:A ⊢ u : B[x := t]       Γ ⊢ t : A
  ----------------------------------------
       Γ ⊢ let x = t in u : B[x := t]
```
Or alternatively, carrying the equality constraint `x ≡ t` in the
context (I think that this is what is done in Coq).

**Comment by fblanqui** [comment] 2019-06-19 11:25
I close it because this is a duplicate of #208 . (Please, check the current issues first before adding a new one.) As mentioned in #208 and above, this is a non trivial change. So, we would need some important non trivial example to justify to do it.

**Closed by fblanqui** 2019-06-19 11:25 UTC
