### ISSUE TITLE
The LSP server does not handle file names with non ASCII characters

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#343] opened 2020-04-08 15:20 UTC
When, in Emacs, I want to look at a file f.lp located in /d1/d2/../dn/, I get no feedback if one of the directory di contains non-ascii characters.

**Comment by fblanqui** [comment] 2020-04-09 07:21
@gabrielhdt do you think that this is related to the Emacs mode?

**Comment by gabrielhdt** [comment] 2020-04-09 07:37
It comes from the LSP server, if we have a look in the logs, 
```
$ tail lambdapi_lsp_log.txt 
            "textDocument": { "uri": "file:///tmp/%CE%B7/f.lp" },
            "position": { "line": 0, "character": 5 }
          }
        }
[[BT]]: Raised at file "hashtbl.ml", line 194, characters 13-28
Called from file "src/lsp/lp_lsp.ml", line 124, characters 61-90
Called from file "src/lsp/lp_lsp.ml", line 291, characters 18-33
Called from file "src/lsp/lp_lsp.ml", line 378, characters 6-44

[process_input]: Not_found
```

**Comment by fblanqui** [comment] 2020-04-09 07:40
Thanks Gabriel. @ejgallego would it be difficult to fix this?

**Comment by rlepigre** [comment] 2020-04-09 09:06
Oh, I removed the `file://` to get the file path, but I did not realise it was percent-encoded. I do not have non-ascii characters on my own files... I can try to fix that if you want. Ideally, it would be nice to implement or use a function that converts a URI into an absolute file path.

**Comment by fblanqui** [comment] 2020-04-09 09:24
Yes, please. Thank you @rlepigre !

**Comment by ejgallego** [comment] 2020-04-09 22:01
Yup, you can find many convenient functions in https://github.com/ocaml/ocaml-lsp so need to roll our own.

**Comment by fblanqui** [comment] 2021-12-15 15:53
This problem seems to be solved now. Perhaps thanks to one of @firewall2142 's contributions.

**Comment by Alidra** [comment] 2024-04-05 07:43
Hi @fblanqui. 
Can we close this issue as the problem is solved? (I tried with Vscode and it works fine too)

**Closed** 2024-04-05 08:44 UTC
Labels: lsp
