### ISSUE TITLE
Bug in parsing with module aliases and declared identifiers

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#429] opened 2020-06-30 15:47 UTC
```
// file lambdapi.pkg
package_name = tmp
root_path = tmp
// file A/B.lp:
set declared "τ"
symbol τ:TYPE
// file bug.lp:
require tmp.A.B as F
symbol x : F.τ
// [/home/blanqui/src/lambdapi/tmp/bug.lp, 2:13] Parse error.
```

**Comment by gabrielhdt** [comment] 2020-06-30 16:12
This is a duplicate of #369.

**Closed by gabrielhdt** 2020-06-30 16:12 UTC
