### ISSUE TITLE
Type annotations on the right-hand side of a rewrite rule

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/lambdapi#220] opened 2019-06-11 09:46 UTC
Currently, a rewrite such as 
```dedukti
A : Type.
def id : A -> A.
[] id --> x => x.
``` 

Does not type check with `lambdapi` because a type annotation is missing on the right-hand side of the rewrite rule. However, the type could be inferred easily. Is there any plan to change that behavior?

**Comment by fblanqui** [comment] 2019-06-18 20:04
This is a duplicate of #169 . Yes, we should fix this.

**Closed by fblanqui** 2019-06-18 20:04 UTC
