### ISSUE TITLE
[Feature Request] Aliases

### ISSUE THREAD

**Issue by thiagofelicissimo** [Deducteam/lambdapi#728] opened 2021-09-21 11:04 UTC
When encoding products of a functional PTSs as in
```
constant symbol ⇝ : Π (s1 s2: Sort) (A : U s1), (El A → U s2) → U (s1 ∨ s2);
```
it is already very helpful to have implicit arguments, so we can instead declare
```
constant symbol ⇝ : Π {s1 s2: Sort} (A : U s1), (El A → U s2) → U (s1 ∨ s2);
notation ⇝ infix left 6;
```
allowing to replace `⇝ Set Prop prop (λ p. p)` by `prop ⇝ (λ p. p)`.

However, it would be even nicer if we had a functionality to declare aliases, for instance like
```
alias ∀ !x : !A. !B ≔ !A ⇝ (λ !x, !B)
```
which then would enable us to replace `prop ⇝ (λ p. p)` by `∀ p : prop. p`, a very clean way of writing the encoding.

**Comment by fblanqui** [comment] 2021-09-22 12:43
This looks like a duplicate of #248. You can declare a symbol to have a "quantifier" notation. See the user manual. I think that it should answer your request, although there currently is some limitation on the use of this notation.

**Closed** 2021-11-22 14:57 UTC
