### ISSUE TITLE
New definitions of notation ignored across files

### ISSUE THREAD

**Issue by melanie-taprogge** [Deducteam/lambdapi#1149] opened 2024-11-11 13:03 UTC
I experienced a problem when overwriting a notation previously set.
When I for instance want to declare a new notation for ∨ (as declared in the standard-library) to make ∨ right- rather than left-associative, I would add a line like...
`notation ∨ infix right 6;`
to my file. It works just fine in the file itself but I experience unexpected behaviour if I require the file with the new notation in another file: Rather than using the notation of the latest required file, the standard-library notation is used once more even if the file with the new notation was the last one to be required.

I will include Lambdapi-files demonstrating this issue.

Thank you!
[example.zip](https://github.com/user-attachments/files/17702715/example.zip)

**Comment by fblanqui** [comment] 2024-11-22 09:00
duplicate of #1116

**Closed by fblanqui** 2024-11-22 09:00 UTC
