### ISSUE TITLE
Including a path from command line

### ISSUE THREAD

**Issue by elhaddadyacine** [Deducteam/lambdapi#93] opened 2018-10-15 12:05 UTC
Does `lambdapi` have an option to include a path that contains `.lpo` like in `dedukti` ?.
```bash
lambdapi file.lp -I /path/to/library
```
If the user wants to include the files he must add a `require` in every `.lp` or copy the library files in the same folder.

**Comment by rlepigre** [comment] 2018-10-15 13:18
For now there is no such option, but it is in my plan to add it at some point.

**Comment by elhaddadyacine** [comment] 2019-07-26 14:53
Hi,
@rlepigre any news about this feature?

**Comment by rlepigre** [comment] 2019-07-30 07:09
Sorry Yacine, I still did not find the time to look into that. In fact I tried something a while ago, but there was a problem I did not foresee (but I don't remember what it was).

Is that really a limitation for you or can you work around this? Can you explain your use case a little bit?

Note that in any case, the user will still need to use a `require` to include files.

**Comment by francoisthire** [comment] 2019-07-30 07:30
But there are two problems, right? The one Yacine mentioned and also that it is not possible to write:
```
lambdapi /foo/file.lp
```
Is it something you want to fix too? What is the problem with the current behavior of Dedukti?

**Comment by rlepigre** [comment] 2019-07-30 08:08
No I don't want to change that. I was thinking of taking a similar approach to what Coq does, and allow for linking a particular folder (with any path, absolute or not) to a module path. So for instance, you could associate the folder `/home/john/.opam/lambdapi/libs/matita` to the module path `matita`.

There is no problem with what Dedukti does, but the approach used in Lambdapi allows for a simple (automatic) management of dependencies. That may change in the future, but that is definitely not a priority project.

**Comment by rlepigre** [comment] 2019-10-18 18:54
Duplicate of #243.

**Closed by rlepigre** 2019-10-18 18:54 UTC
Labels: feature request
