### ISSUE TITLE
Undesired output from parser

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#183] opened 2019-03-06 17:09 UTC
Take the files:

bool.lp:
```
// Type of booleans
symbol const B : TYPE
symbol const true  : B
symbol const false : B
// Negation
symbol not : B ⇒ B
rule not true  → false
 and not false → true
// Disjunction
symbol or : B ⇒ B ⇒ B set infix left 6 "|" ≔ or
rule true | _   → true
 and _ | true   → true
 and false | &b → &b
 and &b | false → &b
// Conjunction
symbol band : B ⇒ B ⇒ B set infix left 7 "&" ≔ band
rule true & &b → &b
 and &b & true → &b
 and false & _ → false
 and _ & false → false
```

and natbool.lp:
```
require open bool
// Boolean equality
symbol beq : N ⇒ N ⇒ B // N is unknown on purpose
rule beq z      z      → true
 and beq (s &m) (s &n) → beq &m &n
 and beq z      (s _)  → false
 and beq (s _)  z      → false
// Boolean less-than
symbol ble : N ⇒ N ⇒ B
rule ble z      z      → false
 and ble z      (s _)  → true
 and ble (s &m) (s &n) → ble &m &n
```

Output:
```
18:08 ~/lambdapi-git/lib lp natbool.lp 
Entering directory '/home/blanqui/src/deducteam/lambdapi-git'
Entering directory '/home/blanqui/src/deducteam/lambdapi-git'
Checked [bool.lp]
merging ( term_<...> * )  at natbool.lp 8:9-8:14
merging ( term_<...> * )  at natbool.lp 8:16-8:21
merging term_<...> → term_<...> *  at natbool.lp 8:5-8:31
merging term_<...> * term_<...>  at natbool.lp 8:25-8:31
merging term_<...> term_<...> *  at natbool.lp 8:25-8:34
merging term_<...> → term_<...> *  at natbool.lp 8:5-8:34
merging term_<...> * term_<...>  at natbool.lp 8:25-8:34
merging ( term_<...> * )  at natbool.lp 18:9-18:14
merging ( term_<...> * )  at natbool.lp 18:16-18:21
merging term_<...> → term_<...> *  at natbool.lp 18:5-18:31
merging term_<...> * term_<...>  at natbool.lp 18:25-18:31
merging term_<...> term_<...> *  at natbool.lp 18:25-18:34
merging term_<...> → term_<...> *  at natbool.lp 18:5-18:34
[natbool.lp, 5:17-18] Unbound symbol or variable [N].
```

**Comment by fblanqui** [comment] 2019-03-06 17:25
Concerning the error message, note that N cannot be a variable here. Why not just saying: Unknown identifier?

**Comment by rlepigre** [comment] 2019-03-06 17:28
Well, the output from the parser basically tell you that there is an ambiguity somewhere. And obviously, if you defined a symbol `"&"` then this is going to collide with the `&` used in pattern variables. Recall that we do not check anything on defined identifiers, so one has to be careful (at least for now).

So to summarize: if you see weird parser messages, you probably messed up with the infix symbols.

**Comment by fblanqui** [comment] 2019-03-06 17:32
I see. But why the parser finds it ambiguous? After all, if & is not immediately followed by an identifier (no space in between), it cannot be a pattern variable.

**Comment by rlepigre** [comment] 2019-03-06 17:37
Good point. Indeed, we defined the grammar as `"&" - ident` so no blanks are allowed. I guess the ambiguity comes from the predictions that the parser makes with a single character look-ahead. In any case, it is a bad idea to use `"&"` as an identifier. At least in the current state.

**Comment by rlepigre** [comment] 2019-03-06 17:43
The problem is legitimate: `(s &m)` can be parsed either as `s` applied to `&m` or as the application of the infix `&` to `s` and `m`. Note that spaces are not enforced around operators. So `n+m`, `n + m` and `n +m` are perfectly valid (assuming a notation `+`).

**Comment by rlepigre** [comment] 2019-03-06 17:45
I close the issue, as this is a documented limitation. Concerning the error message, I am fine with `"identifier"` if you want to change it.

**Closed by rlepigre** 2019-03-06 17:45 UTC

**Comment by fblanqui** [comment] 2019-03-06 17:48
Right. But what do you think of replacing & by, say $, because this is 
really annoying not to allow &, which is a very common symbol?

**Comment by rlepigre** [comment] 2019-03-06 18:22
I think `$` is ugly. There is nothing we can do about it, some symbols are going to be reserved. This is also the case for the implication arrow, and the simple arrow. They are very common too. Note that you can still use `"&&"`, or the logical conjunction symbol.

**Comment by fblanqui** [comment] 2019-03-06 18:26
I disagree. & is much more common. And boolean reflection is used a lot 
in Mathcomp for instance. So we should really make the use of usual 
boolean operators easy.

**Comment by rlepigre** [comment] 2019-03-06 18:32
Why not `~` then? Or `!`? Or backquote?
