### ISSUE TITLE
Newbie issue: mkdir on Mac

### ISSUE THREAD

**Issue by muenchnerkindl** [Deducteam/lambdapi#901] opened 2022-08-02 17:21 UTC
I am getting started with LambdaPi on a Mac and I installed it successfully (I believe) using opam. However, trying to check tutorial.lp either from the command line or from the VS Code Extension, the first problem I run into is that LambdaPi issues a command of the form

mkdir --parent '...'

This syntax is invalid on MacOS, it should be

mkdir -p '...'

I finally realized that it was enough to create the directory from the shell to get around the problem but it would be nice if LambdaPi used the OS-specific command, or if this is too complicated, if the issue could be mentioned in the "Getting started" document.

**Comment by fblanqui** [comment] 2022-08-02 18:31
Hi Stephan. Thank you for your issue. This is a duplicate of https://github.com/Deducteam/lambdapi/issues/896, recently received also. Concerning `lambdapi install`, it has been fixed in the master branch of Lambdapi. But perhaps this problem occurs in some other parts of the code. I didn't take to check this. So with which command did you get this problem?

**Closed** 2022-08-02 18:44 UTC

**Comment by fblanqui** [comment] 2022-08-02 18:45
There was a command that I didn't fix in the previous PR. This should now be done. A new release of lambdapi with the last fixes will be done at the end of August/beginning of September, or perhaps before if I have the time.

**Comment by muenchnerkindl** [comment] 2022-08-03 11:09
Hi Frédéric, thanks for your quick reply, and sorry for having overlooked the existing issue. FYI, I saw the error message as a result of `lambdapi check', not `lambdapi install', but perhaps the two issue the commands via the same method.
