### ISSUE TITLE
LHS with subterm (x y) where x and y are free

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/lambdapi#59] opened 2018-08-24 09:57 UTC
```
A : Type.

a : A.

def f : (A -> A) -> A.

[y] f (x => y y) --> a.
```

I know that it is a syntactic matching and not a HO one, but still I think it should be rejected here.

**Comment by rlepigre** [comment] 2018-08-26 05:50
It it true that we do not make much effort to rejet rules with untypable LHS. However, this is probably not decidable, and personally, this does not bother me at all.

**Comment by francoisthire** [comment] 2018-08-26 08:06
Of course, it is undecidable. But in that case, it might be useful to have at least a warning I think because it might be a mistake made by the user. When you know it is not usable (in the case above it is quite easy to check), I think printing a warning or something might be useful. When you generate Dedukti code for example (including rewrite rules), it is easy to generate a wrong rewrite rule and be puzzled by conversion error. Having a warning from Dedukti might help you to understand where the error comes from.

I am happy when OCaml warn me for unused variables. If I don't like warnings, I can always deactivate warning messages.

**Comment by rlepigre** [comment] 2018-08-26 09:01
Do you have a satisfactory criterion for generating warnings?

**Comment by francoisthire** [comment] 2018-08-26 09:06
In the case above, I think the occur's check rule might be enough. However, if A was definable, it won't be.

Indeed, if A is definable, then the equation "A =?= A -> A" might be solvable one day. 

In general, if you have a constraint "f a1 ... an = g a1 ... an" where "f" and "g" are two static symbols, you know that this equation will never be solvable.

**Comment by rafoo** [comment] 2018-08-26 16:17
I disagree that the LSL cannot be matched. Consider the following:

```
def B : Type.
[] B --> B -> A.
y : B.
#SNF f (x : A => y y).
```

You have to admit however that the rewrite rule `[] B --> B -> A` breaks beta-Gamma strong normalisation.

**Comment by francoisthire** [comment] 2018-08-26 17:39
You're right, I thought that the domain and the codomain of the function should be the same.

**Comment by fblanqui** [comment] 2018-08-27 08:00
Note that your example is not a Miller pattern and should be rejected anyway for this reason. This is a bug that should be fixed.

However, it might be good to emit a warning when a variable is not used indeed, like in OCaml. Unused variables should be replaced by _. We could use a system like in OCaml, with the same error/warning numbers, unless you know a better one. Didn't Coq start to use a similar system too?

Finally, it might be good also to emit a warning when we know that a LHS is not typable.

**Comment by rlepigre** [comment] 2018-08-27 09:04
That is not a bug, but a feature in `lambdapi`. Remember we have syntactic matching as well as Miller patterns.

**Comment by fblanqui** [comment] 2018-08-27 09:36
Right, but we should not accept patterns of the form xy with x and y free. This may lead to too many problems. Many properties are lost when allowing such patterns.

See "Higher-Order Rewrite Systems and their Confluence", Richard Mayr & Tobias Nipkow, TCS 1998, http://doi.org/10.1016/S0304-3975(97)00143-6, p. 5: "For PRSs, the restriction fv ( l ) >= fv ( r ) is preserved under substitution. Thus it has the same effect as for TRSs: rewriting cannot introduce new variables. This fails for general HRSs: although f ( F ( X )) -> g ( X ) meets the restriction, replacing F by \x:Y yields f ( Y ) -> g ( X ) which violates the restriction. This problem is investigated in more detail
by Kahrs [13].

[13] Stefan Kahrs. The variable containment problem. Extended abstract. In Workshop on
Higher-Order Algebra, Logic and Term Rewriting , September 1995.

See also "Higher-order (non-)modularity", C. Appel and V. van Oostrom and J. G. Simonsen, RTA 2010, http://doi.org/10.4230/LIPIcs.RTA.2010.17.

For instance, p. 5: Counterexample 2.3. The disjoint union of the confluent applicative TRSs {g (Z W ) → g W } and {h a → b} is non-confluent as witnessed by g a ← g (h a) → g b.

P. 6: Remark 2.4. The problematic nature of non-pattern rules in applicative TRSs, i.e. rules
which contain active variables as in the first rule in Counterexample 2.3, is well-known.
For instance, adjoining to combinatory logic or the λ-calculus a combinator A defined by
A (Z W ) = Z, i.e. which extracts the function from a function application, immediately
renders these calculi inconsistent in the sense that all terms become convertible [4].

P. 6: Counterexample 2.7. Taking the disjoint union of the applicative left-and-right-linear
typable (non-pattern) TRSs: {f (Z W ) → Z (a f )} and {g (X Y ) → Y (g b)} enables the
non-normalizable reduction f (g b) ↔ g (a f ) despite both TRSs being normalizing.

There are many more interesting examples in this paper.

**Comment by rlepigre** [comment] 2018-08-27 10:02
OK, thanks for the references! I'll look at that when I have a moment.

**Comment by fblanqui** [comment] 2018-08-27 13:30
This issue is mixing many different things. The initial example is no problem for SR. We won't try to detect if a LHS is typable or not, but we may output a warning when we find out that it is not. In this example, we won't. On the other hand, this example shows another problem: the LHS contains a term of the form (x y) where x and y are free variables. I think that we should reject this kind of pattern. So, I will rename the issue accordingly.

**Comment by fblanqui** [comment] 2019-02-12 09:33
Here are the conditions for a rule LHS l to be currently accepted by lambdapi:
- l should be of the form f l1 .. ln (n>=0) [https://github.com/Deducteam/lambdapi/blob/0e6bf87a2a69be0eb368458a7bb99410c33fb3d2/src/scope.ml#L325]
- f should not be declared as a "const" symbol [https://github.com/Deducteam/lambdapi/blob/0e6bf87a2a69be0eb368458a7bb99410c33fb3d2/src/scope.ml#L323]
(note that a warning is output when there is no argument [https://github.com/Deducteam/lambdapi/blob/0e6bf87a2a69be0eb368458a7bb99410c33fb3d2/src/scope.ml#L327]; I see no reason for doing that)
- free variables must be applied to bound variables only [https://github.com/Deducteam/lambdapi/blob/0e6bf87a2a69be0eb368458a7bb99410c33fb3d2/src/scope.ml#L188]

This allows examples like the one of François: x x, where x is free. This allows also: \y, x y y.

Problem: the above conditions are not enough to make sure that a LHS is a Miller pattern.

Question: shouldn't we add some additional checks to enforce this condition?

Reminder: a term is a Miller pattern if its free variables are applied to *distinct* bound variables only. This excludes François' example and \y, x y y as well.

**Comment by francoisthire** [comment] 2019-02-12 09:44
I think this issue is related to @Gaspi's issue created yesterday:
https://github.com/Deducteam/Dedukti/issues/151 . The more general question
than just having a subterm "(x y)" in a pattern is whether we need brackets
in practice.

**Comment by GuillaumeGen** [comment] 2019-02-12 09:53
I think @francoisthire's example is rejected with the rules you presented since `x` is a free variable and is applied to `x` which is not a bound variable.
PS : I will check right now if it is indeed rejected.

**Comment by rlepigre** [comment] 2019-02-12 10:24
Note that a form of _syntactic matching_ is still allowed by Lambdapi, since a pattern variable (with its arguments) can be applied to anything. You can only have variables when you write `&X[x,y,z]` (and indeed, we should check for distinctness), but you can also write things like `&X[x,y] p1 p2 p3` where `p1`, `p2` and `p3` are any valid and well-scoped pattern.

To restrict to miller patterns, more work is needed. That could simply be implemented as a check performed after scoping. However, I think that allowing for more general patterns is a good thing to allow experimenting.

The warning displayed when no arguments are given in a rule is useful in my opinion. This encourages the used of a definition instead of a rule. However, there may be cases where one wants to give several reduction rules to a symbol (for non-deterministic reduction). The reduction engine will however always pick the first one.

**Comment by GuillaumeGen** [comment] 2019-02-12 10:29
>     * free variables must be applied to bound variables only:
https://github.com/Deducteam/lambdapi/blob/0e6bf87a2a69be0eb368458a7bb99410c33fb3d2/src/scope.ml#L188

So Frédéric and I don't understand this checking. What is forbidden by this line of code?

**Comment by fblanqui** [comment] 2019-02-12 10:30
François, I don't see the link with Gaspard's issue and brackets. The 
current issue is about checking whether, in Lambdapi, LHS are Miller 
patterns, as is required in theoretical works on confluence, 
termination, etc. Brackets are a way to help checking that subject 
reduction holds. Please, do not mix every thing.

PS. By the way, it would be nice to stop adding new things into Dedukti!...

Le 12/02/2019 à 10:44, fthire a écrit :

**Comment by fblanqui** [comment] 2019-02-12 10:37
Le 12/02/2019 à 11:24, Rodolphe Lepigre a écrit :
>
> Note that a form of /syntactic matching/ is still allowed by Lambdapi, 
> since a pattern variable (with its arguments) can be applied to 
> anything. You can only have variables when you write |&X[x,y,z]| (and 
> indeed, we should check for distinctness), but you can also write 
> things like |&X[x,y] p1 p2 p3| where |p1|, |p2| and |p3| are any valid 
> and well-scoped pattern.
>
> To restrict to miller patterns, more work is needed. That could simply 
> be implemented as a check performed after scoping. However, I think 
> that allowing for more general patterns is a good thing to allow 
> experimenting.
>
Ok, why not. Then, why checking that free variables are applied to bound 
variables? This could be checked afterwards too. For instance, it is 
useful if one wants to have the eta rule for the sum type: case x 
(\y.F[left y]) (\z.F[right z]) --> F[x]. If we decide to be as liberal 
as possible, then we should only check that l is headed by a function 
symbol, and let the SR, confluence or termination checkers reject 
rewrite systems.


> The warning displayed when no arguments are given in a rule is useful 
> in my opinion. This encourages the used of a definition instead of a 
> rule. However, there may be cases where one wants to give several 
> reduction rules to a symbol (for non-deterministic reduction). The 
> reduction engine will however always pick the first one.
>
>
The same argument applies here. There is no reason to output a warning 
at scoping time.

**Comment by fblanqui** [comment] 2019-02-12 10:40
Sorry Guillaume but I believe I understand what's going on... I 
explained it in my first mail: this code checks that, in a LHS, in 
pattern variables whose syntax is &X[t1,..,tn], the terms t1, .., tn are 
bound variables.

Le 12/02/2019 à 11:29, GuillaumeGen a écrit :

**Comment by francoisthire** [comment] 2019-02-12 10:46
> François, I don't see the link with Gaspard's issue and brackets. The current issue is about checking whether, in Lambdapi, LHS are Miller patterns, as is required in theoretical works on confluence, termination, etc. Brackets are a way to help checking that subject reduction holds. Please, do not mix every thing.

I've deleted my post, but your mail client did not see it. I was indeed completely mistaken.

> PS. By the way, it would be nice to stop adding new things into Dedukti!...

Isn't Lambdapi a code name for Dedukti 3.0?

We can add features on version 2.7 which will be eventually included in version 3.0.

**Comment by rlepigre** [comment] 2019-02-12 10:47
> > ```
> > * free variables must be applied to bound variables only:
> > ```
> 
> [lambdapi/src/scope.ml](https://github.com/Deducteam/lambdapi/blob/0e6bf87a2a69be0eb368458a7bb99410c33fb3d2/src/scope.ml#L188)
> 
> Line 188 in [0e6bf87](/Deducteam/lambdapi/commit/0e6bf87a2a69be0eb368458a7bb99410c33fb3d2)
> 
>  | _       -> fatal t.pos "Not a variable." 
> So Frédéric and I don't understand this checking. What is forbidden by this line of code?
> Is it to have a term which is not a bound variable in meta-variable argument (ie between the brackets)?

We just check that pattern variables (i.e., terms of the form `&X[t1,t2,t3]`) only have bound variables in their environment (i.e., `t1`, `t2` and `t3` are bound variables).

**Comment by fblanqui** [comment] 2019-02-12 10:51
Le 12/02/2019 à 11:46, fthire a écrit :
>
>     PS. By the way, it would be nice to stop adding new things into
>     Dedukti!...
>
> Isn't Lambdapi a code name for Dedukti 3.0?
>
Yes.


> We can add features on version 2.7 which will be eventually included 
> in version 3.0.
>
>
The problem is "eventually" as Dedukti and Lambdapi do not share the 
same code and are not based on the same git repo. We should really limit 
changes on Dedukti as much as possible, and try instead to work on 
Lambdapi as much as possible.

**Comment by rlepigre** [comment] 2019-02-12 10:51
> Ok, why not. Then, why checking that free variables are applied to bound variables? This could be checked afterwards too. For instance, it is useful if one wants to have the eta rule for the sum type: case x (\y.F[left y]) (\z.F[right z]) --> F[x]. If we decide to be as liberal as possible, then we should only check that l is headed by a function symbol, and let the SR, confluence or termination checkers reject rewrite systems.

There is a very good reason for that first limitation: the implementation of matching. And I don't think that it makes much sense to relax that right now. Of course, this may be something to investigate in the future (for the reason you mention).

**Comment by fblanqui** [comment] 2019-02-12 11:45
Le 12/02/2019 à 11:51, Rodolphe Lepigre a écrit :
>
>     Ok, why not. Then, why checking that free variables are applied to
>     bound variables? This could be checked afterwards too. For
>     instance, it is useful if one wants to have the eta rule for the
>     sum type: case x (\y.F[left y]) (\z.F[right z]) --> F[x]. If we
>     decide to be as liberal as possible, then we should only check
>     that l is headed by a function symbol, and let the SR, confluence
>     or termination checkers reject rewrite systems.
>
> There is a very good reason for that first limitation: the 
> implementation of matching. And I don't think that it makes much sense 
> to relax that right now. Of course, this may be something to 
> investigate in the future (for the reason you mention).
>
>

Ok. So, then, we just need to check that variables are distinct and we 
can close this issue. I'll do it.

**Comment by fblanqui** [comment] 2019-02-12 13:04
Done in https://github.com/Deducteam/lambdapi/commit/14ffa76b282b512627b729295d6495da34a105ac.

**Closed by fblanqui** 2019-02-12 13:04 UTC
Labels: discussion
