### ISSUE TITLE
Parsing error with quantifier notation

### ISSUE THREAD

**Issue by QGarchery** [Deducteam/lambdapi#650] opened 2021-04-28 11:51 UTC
The following program 
```
symbol Prop : TYPE;

symbol P : Prop → TYPE;

symbol ∀ : (Prop → Prop) → Prop;
notation ∀ quantifier;

symbol ⇒ : Prop → Prop → Prop;
notation ⇒ infix right 14;

symbol False : Prop ≔ `∀ C, C;

symbol true : TYPE ≔
  P (False ⇒ `∀ C, C);
```
gets rejected with the error message: 
```[(...), 14:13-14] Unexpected token [`].```

It is checked when ``` `∀ C, C``` is put between parentheses but this makes the use of the `quantifier` notation less attractive.

**Comment by yannl35133** [comment] 2021-04-28 12:28
This follows from [the grammar](https://raw.githubusercontent.com/Deducteam/lambdapi/master/docs/syntax.bnf) so the question becomes:
Why are `aterm` and `term` distinct?

**Comment by fblanqui** [comment] 2021-05-04 06:26
I close it because it is a duplicate of https://github.com/Deducteam/lambdapi/issues/430. Please, continue the discussion on #430.

**Closed by fblanqui** 2021-05-04 06:26 UTC
