### ISSUE TITLE
expected relative path

### ISSUE THREAD

**Issue by ckeller** [Deducteam/lambdapi#243] opened 2019-10-10 09:55 UTC
Hi

I would like to call lambdapi on a file which is not in a subdirectory of my working directory, say `/tmp/foo.dk`. However, lambdapi fails with the following error:
```shell
$ lambdapi /tmp/foo.dk 
[unknown location] Invalid path for [/tmp/foo.dk] (expected relative path).
```

I am using the opam package but a quick look at the master branch let me think that it would produce the same answer.

Thank you for your help.

**Comment by fblanqui** [comment] 2019-10-10 10:02
Hello Chantal. This is on purpose. For the moment, LP does not accept file names with absolute paths. Why not running LP in /tmp, or moving your file foo.dk somewhere else?

**Comment by ckeller** [comment] 2019-10-10 10:05
I am calling lambdapi from another tool so
- I do not control the working directory from which lambdapi is called
- I do not want to pollute user's space
Why such a restriction?

**Comment by fblanqui** [comment] 2019-10-10 11:02
Workaround: instead of calling LP directly, use a script that will run LP on the filename part only from the dirname part.
Why such a restriction? @rlepigre shall give you some argument soon hopefully.

**Comment by rlepigre** [comment] 2019-10-10 20:44
The justification for this behavior is that this enforces a correspondence between file path and module path. This simplifies many things, but there are also limitations as you just discovered @ckeller. Of course, this is not satisfactory, and we need some mechanism that:
1) is more permissive,
2) retains some of the good properties we have now for the dependency analysis.

There are several options here:
1) Having a `PATH`-like mechanism (a list of directories to explore in order when looking for a module).
2) Introducing mappings between arbitrary directories and module path prefixes (that is what Coq does to some extend I believe, but it is not always great).

Could you please elaborate a bit on your use case @ckeller:
1) Are your Lambdapi files completely self-contained? If that is the case, then there is an easy workaround.
2) Would a `PATH`-like mechanism suffice for your application?

**Comment by francoisthire** [comment] 2019-10-11 05:55
What are the issues with Coq system? I have the impression that it is
always better to make the distinction between the file system and the
logical path.

Le jeu. 10 oct. 2019 à 22:44, Rodolphe Lepigre <notifications@github.com> a
écrit :

**Comment by ckeller** [comment] 2019-10-11 09:30
Hi @rlepigre 
Thank you for the explanation.

>     1. Are your Lambdapi files completely self-contained? If that is the case, then there is an easy workaround.

No, the objective is to have a prelude in some directory and some other files in other directories. We can as a first step be ok with a self-contained file but not on the longer term. What would the workaround be?

>     2. Would a `PATH`-like mechanism suffice for your application?

Probably, see above for what we need.

**Comment by rlepigre** [comment] 2019-10-11 11:27
> What are the issues with Coq system? I have the impression that it is always better to make the distinction between the file system and the logical path.

@francoisthire the problem is that the user is responsible for doing to many things (e.g., writing a `_CoqProject` file). I would like to have more automation on that front (i.e., a reasonable default behaviour). For instance, given an entry point for the installed libraries (that is a path like `/.../lib/lambdapi`) you could then access the files in inner folders like `stdlib/list.lp` using the qualification `stdlib.list`, and similarly for `matita/blabla.dk`. So installing everything in that particular folder would be enough for Lambdapi to be able to find any installed file in the expected way.

**Comment by rlepigre** [comment] 2019-10-11 11:28
> We can as a first step be ok with a self-contained file but not on the longer term. What would the workaround be?

@ckeller: I'll elaborate later, but I was thinking of running the command `cd dir; lambdapi file.lp` instead of `lambdapi dir/file.lp`.

**Comment by fblanqui** [comment] 2019-10-18 17:48
This issue is a kind of duplicate of #93 . We should close one of the two.

**Comment by fblanqui** [comment] 2019-10-18 17:50
@ckeller did you find a workaround?

**Comment by fblanqui** [comment] 2019-10-18 17:51
@rlepigre we should really do something about that because this is the second time a user stumbles on this issue...

**Comment by ckeller** [comment] 2019-10-20 12:37
@fblanqui For the moment, my workaround is to use dkcheck (I know, it is not going to be developed anymore). I may switch to lambdapi in the next weeks using @rlepigre trick but I admit it would be very useful to be able to call lambdapi independently from the path.

Anyway, thank you for your help and for developping lambdapi!

**Comment by fblanqui** [comment] 2019-11-14 17:23
Hello @rlepigre . Do you think you can handle this issue soon?

**Comment by rlepigre** [comment] 2019-11-14 23:30
Yeah, I'm gonna try to do that before the end of the month.

**Closed** 2020-03-20 16:55 UTC
Labels: high priority
